### ISSUE TITLE
addition of conditional statements in html-files when yml-key are missing

### ISSUE THREAD

**Issue by laurianvm** [vliz-be-opsci/vliz-be-jekyll-theme#5]
example yml:
```yaml
title: "Our conventions"
#clickthrough_button_text: 
#clickthrough_button_url: 
items:
    - title: A
    - title: B
```
used in combination with main.html in simple_colored_boxes still renders a clickthrough button - an ugly one

For all html files were this is relevant, could conditional statement be added to prevent this?
e.g.
```html
{% if data.clickthrough_url and data.clickthrough_button_text %}
<div class="more-link">
  <a href="{{ data.clickthrough_url }}">{{ data.clickthrough_button_text }}</a>
</div>
{% endif %}
```
